name: Deploy Flask App to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Login no Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build e push da imagem para Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: seu-usuario/flask-app:latest

      - name: Deploy com Terraform
        working-directory: ./terraform
        run: |
          terraform init
          terraform apply -auto-approve
